baseURL = 'https://mahmutoklu.github.io/'
locale = 'en-us'
title = 'Mahmut Oklu Technical Blog'
theme = 'LoveIt'

[params]

  [params.author]
    name = 'Mahmut Oklu'
    email = ''
    link = ''

  [params.home]
    [params.home.profile]
      enable = true
      title = 'Mahmut Oklu'
      subtitle = 'System Admin'
      typeit = true
      social = true
      avatarURL = "/Users/mahmutoklu/Documents/mahmutoklu.jpg"
  [params.social]
    GitHub = 'oklumahmut'
    X = ''
    Twitter = ''
    Linkedin = 'https://www.linkedin.com/in/mahmut-oklu/'
    Googlescholar = ''
    Researchgate = ''
    Instagram = 'mahmutoklu'
    Youtubechannel = ''
    Email = 'oklumahmut@hotmail.com'
    RSS = true

