baseURL = 'https://mahmutoklu.github.io/'
locale = 'en-us'
title = 'Mahmut Oklu Technical Blog'
theme = 'LoveIt'

[params]

  [params.author]
    name = 'Mahmut Oklu'
    email = ''
    link = ''

  [params.home]
    [params.home.profile]
      enable = true
      title = 'Mahmut Oklu'
      subtitle = 'System Admin'
      typeit = true
      social = true
      avatarURL = "/images/mahmutoklu.jpeg"
  [params.social]
    GitHub = 'mahmutoklu'
    X = ''
    Twitter = ''
    Linkedin = 'mahmut-oklu'
    Googlescholar = ''
    Researchgate = ''
    Instagram = 'mahmutoklu'
    Youtubechannel = ''
    Email = 'oklumahmut@hotmail.com'
    RSS = true


[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    title = "Posts"
    weight = 1

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    title = "Projects"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    title = "About"
    weight = 3

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    title = "Home"
    weight = 0

  description = "Mahmut Oklu Technical Blog"

  [params.app]
    title = "Mahmut Oklu Technical Blog"
    noFavicon = false

  [params.header]
    [params.header.title]
      name = ""
